version: '3.5'

services:
  postgres:
    image: postgres:16-alpine
    container_name: grouped-catalog
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"